# Generated by Django 2.2.1 on 2019-05-08 14:43

import Democritus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('poll_type', models.CharField(choices=[('RK', 'Ranked'), ('SO', 'Select One'), ('YN', 'Yes/No')], default='SO', max_length=2)),
                ('start_date', models.DateTimeField(verbose_name='Start Time')),
                ('end_date', models.DateTimeField(verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='uploaded_files', validators=[Democritus.models.StudentList.validate_list])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
